#!/bin/bash
# ============================================================
# RunPod Template — AI Video Clip Generator
# Full setup: ComfyUI + WAN models + Gradio UI
#
# Usage: Run this script on a fresh RunPod pod (RTX 4090/6000 Ada)
#   curl -sSL https://raw.githubusercontent.com/<user>/ai-video-clip-generator/main/runpod_template.sh | bash
#
# Environment variables (set in RunPod template):
#   GEMINI_API_KEY  — Google Gemini API key (required)
#   RUNPOD_POD_ID   — Auto-set by RunPod
# ============================================================
set -e

APP_DIR="/workspace/ai-video-clip-generator"
COMFY_DIR="/workspace/runpod-slim/ComfyUI"
VENV_PY="$COMFY_DIR/.venv/bin/python"
VENV_PIP="$COMFY_DIR/.venv/bin/pip"
LOG="/workspace/setup.log"

echo "============================================" | tee "$LOG"
echo " AI Video Clip Generator — RunPod Setup"    | tee -a "$LOG"
echo " $(date)"                                    | tee -a "$LOG"
echo "============================================" | tee -a "$LOG"

# ── 1. Clone/update the app ──────────────────────────────────────────────────
echo "" | tee -a "$LOG"
echo "[1/6] Cloning app repository..." | tee -a "$LOG"

if [ -d "$APP_DIR/.git" ]; then
    cd "$APP_DIR" && git pull --ff-only 2>&1 | tee -a "$LOG"
    echo "[OK] App updated" | tee -a "$LOG"
else
    # If dir exists but no git, back up and re-clone
    [ -d "$APP_DIR" ] && mv "$APP_DIR" "${APP_DIR}.bak.$(date +%s)"
    git clone https://github.com/<user>/ai-video-clip-generator.git "$APP_DIR" 2>&1 | tee -a "$LOG"
    echo "[OK] App cloned" | tee -a "$LOG"
fi

cd "$APP_DIR"

# ── 2. Install Python dependencies (system pip, not ComfyUI venv) ────────────
echo "" | tee -a "$LOG"
echo "[2/6] Installing Python dependencies..." | tee -a "$LOG"

pip install -q -r requirements.txt 2>&1 | tee -a "$LOG"
echo "[OK] Python deps installed" | tee -a "$LOG"

# ── 3. Install Whisper (optional — heavy, skip if transcription is remote) ───
echo "" | tee -a "$LOG"
echo "[3/6] Installing OpenAI Whisper..." | tee -a "$LOG"

if ! python -c "import whisper" 2>/dev/null; then
    pip install -q openai-whisper 2>&1 | tee -a "$LOG"
    echo "[OK] Whisper installed" | tee -a "$LOG"
else
    echo "[SKIP] Whisper already installed" | tee -a "$LOG"
fi

# ── 4. Setup ComfyUI models & custom nodes ───────────────────────────────────
echo "" | tee -a "$LOG"
echo "[4/6] Setting up WAN models for ComfyUI..." | tee -a "$LOG"

if [ -d "$COMFY_DIR" ]; then
    bash "$APP_DIR/setup_wan_comfyui.sh" 2>&1 | tee -a "$LOG"
    echo "[OK] Models setup complete" | tee -a "$LOG"
else
    echo "[WARN] ComfyUI not found at $COMFY_DIR" | tee -a "$LOG"
    echo "       Use a RunPod template with ComfyUI pre-installed" | tee -a "$LOG"
fi

# ── 5. Write .env from RunPod environment ─────────────────────────────────────
echo "" | tee -a "$LOG"
echo "[5/6] Configuring environment..." | tee -a "$LOG"

cat > "$APP_DIR/.env" << EOF
# Auto-generated by runpod_template.sh — $(date)
RUNPOD_POD_ID=${RUNPOD_POD_ID:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
COMFYUI_BASE_URL=https://${RUNPOD_POD_ID}-8188.proxy.runpod.net
COMFYUI_WS_URL=wss://${RUNPOD_POD_ID}-8188.proxy.runpod.net/ws
EOF
echo "[OK] .env written" | tee -a "$LOG"

# Source .env for the app
set -a && source "$APP_DIR/.env" && set +a

# ── 6. Start services ────────────────────────────────────────────────────────
echo "" | tee -a "$LOG"
echo "[6/6] Starting services..." | tee -a "$LOG"

# Start ComfyUI (if not already running)
if ! pgrep -f "main.py --listen" > /dev/null && [ -d "$COMFY_DIR" ]; then
    cd "$COMFY_DIR"
    nohup $VENV_PY main.py --listen 0.0.0.0 --port 8188 --preview-method auto \
        > /workspace/comfyui.log 2>&1 &
    echo "[OK] ComfyUI starting on port 8188" | tee -a "$LOG"
    sleep 5
fi

# Start Gradio UI
cd "$APP_DIR"
nohup python ui.py --server-name 0.0.0.0 --port 7860 --no-browser \
    > /workspace/gradio.log 2>&1 &

echo "[OK] Gradio UI starting on port 7860" | tee -a "$LOG"

echo ""
echo "============================================"
echo " SETUP COMPLETE"
echo ""
echo " ComfyUI:  https://${RUNPOD_POD_ID}-8188.proxy.runpod.net"
echo " Gradio:   https://${RUNPOD_POD_ID}-7860.proxy.runpod.net"
echo ""
echo " Logs:"
echo "   ComfyUI: tail -f /workspace/comfyui.log"
echo "   Gradio:  tail -f /workspace/gradio.log"
echo "   Setup:   cat $LOG"
echo "============================================"
